# Generated by Django 5.2.6 on 2025-09-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_patientdoctormapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
